# Generated by Django 4.1.7 on 2023-07-03 06:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("cas_number", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("inci_name", models.CharField(blank=True, max_length=255, null=True)),
                ("more_info", models.TextField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("organic", models.BooleanField(null=True)),
                ("pubmed_count", models.IntegerField(blank=True, null=True)),
                (
                    "pubmed_term",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("usage", models.TextField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WarningAgency",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "jurisdiction",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        default="Ссылки на источник временно недоступны",
                        null=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("short_name", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warning_agencies",
                        to="mainapp.ingredient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        default="Ссылки на источник временно недоступны",
                        null=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("short_name", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="mainapp.ingredient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngredientAliasName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_alias_names",
                        to="mainapp.ingredient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hazard",
            fields=[
                ("benefit", models.BooleanField()),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("short_name", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hazards",
                        to="mainapp.ingredient",
                    ),
                ),
            ],
        ),
    ]
