# Generated by Django 4.1.7 on 2023-07-03 06:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_ingredient_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hazard",
            name="benefit",
        ),
    ]
