# Generated by Django 4.1.7 on 2023-07-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_remove_hazard_benefit"),
    ]

    operations = [
        migrations.AddField(
            model_name="hazard",
            name="benefit",
            field=models.BooleanField(null=True),
        ),
    ]
